### Requisição de cadastro
POST http://localhost:3000/cidade
Content-Type: application/json

{
  "nome": "BBBBBBB"
}


### Requisição de listagem
GET http://localhost:3000/cidade


### Requisição de consulta por ID
GET http://localhost:3000/cidade/


### Requisição de edição
PATCH http://localhost:3000/cidade/
Content-Type: application/json

{
  "nome": "",
}


### Requisição de exclusão
DELETE http://localhost:3000/cidade/