###
GET http://localhost:3000/tipo-instituicao

###
GET http://localhost:3000/tipo-instituicao/1


###
POST http://localhost:3000/tipo-instituicao
Content-Type: application/json

{
    "descricao": "Xablau"
}

###
PATCH http://localhost:3000/tipo-instituicao/1

###
DELETE http://localhost:3000/tipo-instituicao/2