###
GET http://localhost:3000/instituicao

###
GET http://localhost:3000/instituicao/6


###
POST http://localhost:3000/instituicao
Content-Type: application/json

{
   "nome": 12,
    "sigla": "USCS"
}


###
PATCH http://localhost:3000/instituicao/6
Content-Type: application/json

{
   "nome": "USCS1-EDITADO",
   "sigla": "USCS1"
}
###
DELETE http://localhost:3000/instituicao/7