###
GET http://localhost:3000/tipo-instituicao


###
GET http://localhost:3000/


###
POST http://localhost:3000/tipo-instituicao
Content-Type: application/json

{
   "descricao": 1
}


###
PATCH http://localhost:3000/
Content-Type: application/json

{
   
}


###
DELETE http://localhost:3000/