### Requisição de cadastro
POST http://localhost:3000/juridica
Content-Type: application/json

{
  "cnpj": "",
  "social": "",
  "fantasia": "",  
  "email": "",
}


### Requisição de listagem
GET http://localhost:3000/juridica


### Requisição de consulta por ID
GET http://localhost:3000/juridica/


### Requisição de edição
PATCH http://localhost:3000/juridica/
Content-Type: application/json

{
  "cnpj": "",
  "social": "",
  "fantasia": "",
  "email": "",
}


### Requisição de exclusão
DELETE http://localhost:3000/juridica/

